### ISSUE TITLE
Not usable within containers

### ISSUE THREAD

**Issue by mohsinhijazee** [eminence/procfs#65]
Really nice library - however, I miss that it cannot work inside containers because it would be looking at the global stats. Am I misunderstanding the API here? Because as far as my understanding is concerned, it is under `/sys/fs/cgroup/*` namespace.

I'd like to see that part of this library as well. Any thoughts or recommendations on the API design are most welcome and I am willing to contribute to the crate starting with memory and CPU stats.

**Comment by eminence** [comment]
Hi.  Could you say some more about what things don't currently work in a container, or what new features you'd like to see added?  

In general, the `/proc/` file system is container-aware (and so `procfs` will be container-aware).  For example, from within a container, you can't see the other network connections on the host machine:

    docker run --rm -it ubuntu:latest cat /proc/self/net/tcp

Or, if using procfs, compare the output of:

    ./target/debug/examples/netstat

To the output of:

    docker run --rm -it -v `pwd`/target/debug/examples:/examples ubuntu:latest /examples/netstat

**Comment by mohsinhijazee** [comment]
@eminence Thank you for your quick response. My understanding is that `/proc` is not container specific and if on any container orchestration tool you read files in this directory _from within the container_ - they will show you the overall status for the machine and not for the container in which this prob is made. 

Imagine a container that is running with a limit of 128 MB and for that:

`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`

from within container returns 134217728 which is 128 MB. But from within that container, if you do:

` cat /proc/meminfo `

Then the memory is reported like this:
```
MemTotal:       15950512 kB
.... other lines skipped
```
 which is roughly 16 GB - the memory of the node on which this container is running. 

So that is what I mean by _not working in the conainer_ which probably is not the right label. More accurate would be to say that container specific metrics are not being read.

What do you suggest API wise where these should go?

**Comment by eminence** [comment]
Yes, it's true that for memory info, you need to look at the container group itself (as you show well in your comment).

For this, procfs only partially helps.  You can use `Process::cgroups()` to see what groups the process is a member of, and you can use a combination of `procfs::cgroups()` and `Process::mountinfo()` to figure out where to find the cgroup mount (for example "/sys/fs/cgroup/memory/").

But at this point, procfs doesn't help because it doesn't parse any of the files made available by the various container controller.  So you'd have to parse the "memory.usage_in_bytes" file yourself.

I would certainly welcome contributions in this area.  I haven't thought much about the API, but maybe each container controller would get its own struct, which you would construct with a path, and you'd be able to access the data with various accessor methods.   For some controllers, this is probably easy.  For others, it would be a lot of work (for example, the memory controller exports hundreds of stats)

I personally would like to have something like this for another [personal project](https://github.com/eminence/procdump).  It also gets info about a running process, so feel free to borrow any of its code for your own project.

**Comment by eminence** [comment]
I think this question is answered, so I"m going to close the issue.  Thanks!
