### ISSUE TITLE
Signage of Stat::pid, Stat::gid etc. 

### ISSUE THREAD

**Issue by ahmed-masud** [eminence/procfs#85]
Hey there! :-) 

Question why did you chose to do a pid: i32

https://github.com/eminence/procfs/blob/777751564c01f08ba0bf986eb31e8447301d1ac2/src/process/stat.rs#L27

(and similarly gid, etc. as i32)? 

I ask because in linux `pid_t` is unsigned.

**Comment by eminence** [comment]
Hello!   

It's true that process IDs themselves are unsigned, but the main reason that pids are `i32` is because in libc they are `i32`:  https://docs.rs/libc/0.2.71/libc/type.pid_t.html

Why is the `pid_t` type signed in linux libc?  One reason is that functions like `fork` will [return](https://man7.org/linux/man-pages/man2/fork.2.html) a `pid_t`, but also return `-1` on error.

**Comment by ahmed-masud** [comment]
Never mind!
